### ISSUE TITLE
Scraped html does not match the url - chrome [with_wait_for_idle_network]

### ISSUE THREAD

**Issue by esemeniuc** [spider-rs/spider#166] opened 2024-02-20 03:25 UTC
Using 1.82.4, when running the code below, the url doesn't match the page contents. It seems to mix up urls for different pages when inspecting the contents. So far it works fine on `https://rsseau.fr`, but it has trouble on the url below. Do I need to use `website.subscribe_guard()`?

```rust
//    crawl_and_scrape_urls("https://docs.drift.trade").await;
pub async fn crawl_and_scrape_urls(webpage: &str) {
    let mut website: Website = Website::new(webpage)
        .with_chrome_intercept(cfg!(feature = "chrome_intercept"), true)
        .with_wait_for_idle_network(Some(WaitForIdleNetwork::new(Some(Duration::from_secs(30)))))
        .with_caching(cfg!(feature = "cache"))
        .with_delay(200)
        .build()
        .unwrap();
    let mut rx2 = website.subscribe(16).unwrap();

    // website.subscribe_guard()
    let start = Instant::now();
    tokio::spawn(async move {
        while let Ok(page) = rx2.recv().await {
            println!("found {:?}, size: {}, is_some:{}, status:{:?}, {:?}", page.get_url(), page.get_bytes().map(|b| b.len()).unwrap_or_default(), page.get_bytes().is_some(), page.status_code, start.elapsed());
            fs::write(page.get_url_final().replace("/", "__"), page.get_html()).expect("Unable to write file");
        }
    });

    // crawl the site first
    website.crawl().await;
    // persist links to the next crawl
    website.persist_links();
    // scrape all discovered links
    website.scrape().await;
}
```

**Comment by j-mendez** [comment] 2024-02-20 15:12
Hi @esemeniuc , thanks for the issue! It looks like `with_wait_for_idle_network` causes the page to lose focus. Now fixed in `v1.82.5`.

**Comment by esemeniuc** [comment] 2024-02-20 15:15
Thank you very much :1st_place_medal:

**Comment by esemeniuc** [comment] 2024-02-20 15:52
Just retested on version 1.82.5, for example, `page.get_url_final()` outputted https://docs.drift.trade/liquidations/liquidations , but the page content is for https://docs.drift.trade/security/bug-bounty

**Comment by esemeniuc** [comment] 2024-02-20 15:53
here is the crawl ordering:
```
found "https://docs.drift.trade", size: 191972, is_some:true, status:200, 1.425570057s
found "https://docs.drift.trade/profit-loss/accounting-settlement", size: 188437, is_some:true, status:200, 5.623358851s
found "https://docs.drift.trade/liquidations/liquidations", size: 188437, is_some:true, status:200, 5.668653165s
found "https://docs.drift.trade/developer-resources/tutorial-bots/troubleshooting", size: 188437, is_some:true, status:200, 5.687482929s
found "https://docs.drift.trade/providing-liquidity/dlp-drift-liquidity-provider", size: 188437, is_some:true, status:200, 5.704037773s
found "https://docs.drift.trade/trading/spot-margin-trading", size: 188437, is_some:true, status:200, 5.722658013s
found "https://docs.drift.trade/trading/order-types", size: 188437, is_some:true, status:200, 5.739990372s
found "https://docs.drift.trade/about-v2/understanding-drift", size: 188437, is_some:true, status:200, 5.756607324s
found "https://docs.drift.trade/security/bug-bounty", size: 188437, is_some:true, status:200, 5.77306084s
found "https://docs.drift.trade/developer-resources/tutorial-bots/keeper-bots/tutorial-order-matching-bot", size: 188437, is_some:true, status:200, 5.79006861s
found "https://docs.drift.trade/developer-resources/tutorial-bots/keeper-bots", size: 188437, is_some:true, status:200, 5.816038455s
found "https://docs.drift.trade/about-v2/keepers-decentralized-orderbook-faq", size: 188437, is_some:true, status:200, 5.835567478s
found "https://docs.drift.trade/developer-resources/API", size: 188437, is_some:true, status:200, 5.85183601s
found "https://docs.drift.trade/legal-and-regulations/competition-terms", size: 188437, is_some:true, status
```

**Comment by esemeniuc** [comment] 2024-02-20 15:53
looks like during the crawl, they were very near each other in time

**Comment by j-mendez** [comment] 2024-02-20 19:15
Hi @esemeniuc can you try out `v1.82.7`?. If that does not fix the issue most likely going to remove the option. I currently cannot reproduce the issue after `v1.82.7` with  `https://docs.drift.trade`. Pardon the extra request to test on the url!

**Comment by esemeniuc** [comment] 2024-02-21 01:09
Sure, I can test in 1h

**Comment by j-mendez** [comment] 2024-02-21 01:54
> Sure, I can test in 1h

FYI  In `v1.83.0` you can now set a hard delay to wait using `wait_for_with_delay` and wait_for_selector_with_selector`.

**Comment by esemeniuc** [comment] 2024-02-21 04:43
I just tried to run 1.82.7 and 1.83.0, both seem to hang without progress

**Comment by esemeniuc** [comment] 2024-02-21 04:43
My cargo.toml is `spider = { version = "=1.83", features = ["chrome"] }`

**Comment by esemeniuc** [comment] 2024-02-21 04:50
I closed all other chrome instances, still no logs.

**Comment by esemeniuc** [comment] 2024-02-21 04:50
Running with `RUST_LOG=trace` it hangs on 
```
[2024-02-21T04:49:41Z TRACE tungstenite::protocol] Received message {"method":"Page.lifecycleEvent","params":{"frameId":"B567CFFA2CCC103752A66D6C3857DBFA","loaderId":"127318450D455960D0253111906D545A","name":"firstMeaningfulPaint","timestamp":200174.819054},"sessionId":"ACBEF2992F1E17A8D031AB67E08CEF6A"}
[2024-02-21T04:49:41Z TRACE tungstenite::protocol::frame::frame] Parsed headers [129, 126]
[2024-02-21T04:49:41Z TRACE tungstenite::protocol::frame::frame] First: 10000001
[2024-02-21T04:49:41Z TRACE tungstenite::protocol::frame::frame] Second: 1111110
[2024-02-21T04:49:41Z TRACE tungstenite::protocol::frame::frame] Opcode: Data(Text)
[2024-02-21T04:49:41Z TRACE tungstenite::protocol::frame::frame] Masked: false
[2024-02-21T04:49:41Z TRACE tungstenite::protocol::frame] received frame 
    <FRAME>
    final: true
    reserved: false false false
    opcode: TEXT
    length: 230
    payload length: 226
    payload: 0x7b226d6574686f64223a22506167652e6c6966656379636c654576656e74222c22706172616d73223a7b226672616d654964223a224235363743464641324343433130333735324136364436433338353744424641222c226c6f616465724964223a223132373331383435304434353539363044303235333131313930364435343541222c226e616d65223a226e6574776f726b49646c65222c2274696d657374616d70223a3230303137352e313236367d2c2273657373696f6e4964223a224143424546323939324631453137413844303331414236374530384345463641227d
                
[2024-02-21T04:49:41Z TRACE tungstenite::protocol] Received message {"method":"Page.lifecycleEvent","params":{"frameId":"B567CFFA2CCC103752A66D6C3857DBFA","loaderId":"127318450D455960D0253111906D545A","name":"networkIdle","timestamp":200175.1266},"sessionId":"ACBEF2992F1E17A8D031AB67E08CEF6A"}
[2024-02-21T04:49:44Z TRACE tungstenite::protocol::frame::frame] Parsed headers [129, 126]
[2024-02-21T04:49:44Z TRACE tungstenite::protocol::frame::frame] First: 10000001
[2024-02-21T04:49:44Z TRACE tungstenite::protocol::frame::frame] Second: 1111110
[2024-02-21T04:49:44Z TRACE tungstenite::protocol::frame::frame] Opcode: Data(Text)
[2024-02-21T04:49:44Z TRACE tungstenite::protocol::frame::frame] Masked: false
[2024-02-21T04:49:44Z TRACE tungstenite::protocol::frame] received frame 
    <FRAME>
    final: true
    reserved: false false false
    opcode: TEXT
    length: 236
    payload length: 232
    payload: 0x7b226d6574686f64223a22506167652e6c6966656379636c654576656e74222c22706172616d73223a7b226672616d654964223a224235363743464641324343433130333735324136364436433338353744424641222c226c6f616465724964223a223132373331383435304434353539363044303235333131313930364435343541222c226e616d65223a22496e74657261637469766554696d65222c2274696d657374616d70223a3230303138302e3032323938367d2c2273657373696f6e4964223a224143424546323939324631453137413844303331414236374530384345463641227d
                
[2024-02-21T04:49:44Z TRACE tungstenite::protocol] Received message {"method":"Page.lifecycleEvent","params":{"frameId":"B567CFFA2CCC103752A66D6C3857DBFA","loaderId":"127318450D455960D0253111906D545A","name":"InteractiveTime","timestamp":200180.022986},"sessionId":"ACBEF2992F1E17A8D031AB67E08CEF6A"}
y
```

**Comment by esemeniuc** [comment] 2024-02-21 04:52
Running with `RUST_LOG=debug`, it hangs on:
```
/usr/bin/cargo run --color=always --package scraper --bin scraper
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/scraper`
[2024-02-21T04:51:33Z DEBUG tungstenite::handshake::client] Client handshake done.


```

**Comment by esemeniuc** [comment] 2024-02-21 04:54
If I disable `.with_wait_for_idle_network()`, it appears to work

**Comment by j-mendez** [comment] 2024-02-21 11:45
@esemeniuc attempt  1000 😅, was able to fix the page hanging. It seems that it only happens on certain websites  - moving the wait_for_navigation event after the idle network seems to have been a problem. The wait_for_navigation method does not handle the case if it is already loaded. The frames would mess up from the concurrency on the page ( we only use one tab to drive the entire crawl and just intercept the frames ). Closing the page at the end fixes the frames messing up when delays occur.

Can you `v1.83.1`?

**Comment by j-mendez** [comment] 2024-02-23 19:52
fixed `v1.83.11`

**Comment by j-mendez** [comment] 2024-02-24 00:56
Can now confirm the fix in `v1.84.0`. We now use top level browser events and new page handling.

**Closed by j-mendez** 2024-02-24 00:56 UTC

**Comment by esemeniuc** [comment] 2024-02-24 17:11
Works perfectly, thank you very much @j-mendez :) :)

**Comment by j-mendez** [comment] 2024-02-24 17:24
> Works perfectly, thank you very much @j-mendez :) :)

Np, thank you for the help!
