### ISSUE TITLE
Add DEPTH level next to each debug line [ENHANCEMENT]

### ISSUE THREAD

**Issue by Zabrane** [spider-rs/spider#185] opened 2024-05-30 07:56 UTC
Hi @j-mendez 

Would it be possible to add the depth level next to each URL when `--depth` is used?
Something like this
```bash
$ spider --verbose --depth 2 --url "https://choosealicense.com/" crawl
[2024-05-30T07:53:11Z INFO  spider::utils] fetch - depth 1 - https://choosealicense.com/
[2024-05-30T07:53:11Z INFO  spider::utils] fetch - depth 2 -https://choosealicense.com/non-software/
[2024-05-30T07:53:11Z INFO  spider::utils] fetch - depth 2 -https://choosealicense.com/licenses/
[2024-05-30T07:53:11Z INFO  spider::utils] fetch - depth 2 -https://choosealicense.com/about/
...
```

This will help me ensure that the `--depth` is enforced during the crawl.
I can perform more tests to ensure all options are working as expected.

Finally, what's the logic when both `--limit` and `--depth` are used? I assume that when one of them reaches its max, the crawl will stop. Am i right?

Thanks

**Comment by j-mendez** [comment] 2024-05-30 13:37
Depth is only used to determine what links are acceptable from the root crawl and does not stop the crawl. I think if it is not working as intended we just need fix the issue instead of adjusting the base log out. Going to close this one since the log output we do not want to add any cpu processing unless critical. https://docs.rs/env_logger/latest/env_logger/#example

**Closed by j-mendez** 2024-05-30 13:37 UTC

**Comment by Zabrane** [comment] 2024-05-30 15:10
@j-mendez Ah so `--depth` is still buggy.

**Comment by failable** [comment] 2024-06-05 03:56
Have trouble understanding how `depth` works.
